# Generated by Django 3.2.6 on 2021-08-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_ativo_usuario_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='situacao',
        ),
    ]
